expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
exposecontroller:
  config:
    domain: 218.93.250.18.nip.io
    exposer: Ingress
    http: "true"
    tlsacme: ""
    pathmode: ""
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  servers:
    gitea: []
    ghe: []
    global:
      envvars:
        DOCKER_REGISTRY: 255649138826.dkr.ecr.us-east-2.amazonaws.com
        TILLER_NAMESPACE: kube-system
  enabled: null
prow:
  user: ""
  hmactoken: ""
  oauthtoken: ""
pipelinesecrets:
  dockerconfig: ""
controllerbuild:
  enabled: null
